---
- name: Install puma service
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  tags: puma
- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify:
    - restart puma
  tags: puma
  
- name: enable puma.service
  systemd:
    daemon-reload: true
    name: puma
    enabled: true
